### ISSUE TITLE
On bind, service broker loads bind host into the org/space policy

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-service-broker#63]
ETA for completion of this story: Feb 5, 2019
Confidence level of ETA accuracy: 90%

## Changes to customer recommendations
At current, we advise end-users to create a special policy branch to load hosts and integration-related policy:
```
- !policy
  id: cf
  owner: !group cf-admin-group
  body:
   - !layer cf-apps

   - !host-factory
     id: cf-apps
     layers: [ !layer cf-apps ]
```

As part of this update, end-users will also upload a `foundation` policy branch where individual `org` policy branches may be loaded, and the individual `org` branches may also contain multiple `space` policy branches (mirroring the layout of applications in CF deployments).

See the XDD workflow here for more information and example of the policy structure:
https://gist.github.com/micahlee/61e9b4fae56726e3e5e3e6d22d8b25bc

## Changes to Service Broker workflows

As part of these updates, the service broker workflows will be updated as follows.

On bind, the service broker parses the bind context sent with the bind request for the org and space GUIDs The expected structure of this context is:

```json
{
  "service_id": "c024e536-6dc4-45c6-8a53-127e7f8275ab",
  "plan_id": "3a116ac2-fc8b-496f-a715-e9a1b205d05c.community",
  "app_guid": "dd8eece4-f835-4503-8171-976c3abe7b8c",
  "bind_resource": {
    "app_guid": "dd8eece4-f835-4503-8171-976c3abe7b8c",
    "space_guid": "48dbfee4-6c42-42e5-961a-0d283ce4a8a4"
  },
  "context": {
    "platform": "cloudfoundry",
    "organization_guid": "4fafc1a6-48b8-45ad-9b73-f81edd7e78d8",
    "space_guid": "48dbfee4-6c42-42e5-961a-0d283ce4a8a4"
  },
  "controller": "bind",
  "action": "put",
  "instance_id": "f72f6d69-c62b-416e-96a1-ac2fe0ffa1c3",
  "binding_id": "a91d9058-2736-4050-ac20-bf3bc0eb8272",
  "bind": {
    "service_id": "c024e536-6dc4-45c6-8a53-127e7f8275ab",
    "plan_id": "3a116ac2-fc8b-496f-a715-e9a1b205d05c.community",
    "app_guid": "dd8eece4-f835-4503-8171-976c3abe7b8c",
    "bind_resource": {
      "app_guid": "dd8eece4-f835-4503-8171-976c3abe7b8c",
      "space_guid": "48dbfee4-6c42-42e5-961a-0d283ce4a8a4"
    },
    "context": {
      "platform": "cloudfoundry",
      "organization_guid": "4fafc1a6-48b8-45ad-9b73-f81edd7e78d8",
      "space_guid": "48dbfee4-6c42-42e5-961a-0d283ce4a8a4"
    }
  }
}

```

The context keys we want to extract are:
- `.app_guid`
- `.context.organization_guid`
- `.context.space_guid`

There are two service broker behaviors possible depending on the presence or not of these keys.

### Backwards Compatibility 

If the GUIDs are not present, the bind continues with no further action related to the org / space (this will help maintain backward functionality with older CF versions).

This means that a host representing the `binding_id` will be added directly to the foundation policy with no automatic entitlement.

### Updated Capability

If the context GUIDs are present, the service broker will perform the following actions:

- Check if a layer with ID given by the org name exists in the `orgs` policy branch. If not, load an `org` sub-policy for this org name in the `foundation` branch, which may look like:
  ```
  - !policy
    id: ORG_GUID
    body:
    - !layer
  ```

- Check if a layer with ID given by the space name exists in the `ORG_NAME` policy branch. If not, load a `space` sub-policy for this space name in the `ORG_NAME` branch, which may look like:
  ```
  - !policy
    id: SPACE_GUID
    body:
    - !layer
  ```

- Generate and load a policy to define a host for the `app_guid` and grant it to the `!layer` for the space

> NOTE: This issue assumes that the policy for the Org and Space exist beforehand, and only checks for their existence. A follow up issue (#70) add automatic creation of these policies when the service broker is provision in a given space.

AC:
- [ ] Flows are implemented to create host and add to space layer on bind
- [ ] Unit (RSpec) tests verify new org/space/app binding functionality
- [ ] Unit (RSpec) tests verify backward compatibility when no org/space context is present 
- [ ] Unit (RSpec) tests verify Conjur V4 functionality is maintained
- [ ] Integration (Cucumber) tests verify new functionality
- [ ] Integration (Cucumber) tests verify backward compatibility when no org/space context is present 
- [ ] Integration (Cucumber) tests verify Conjur V4 functionality is maintained
- [ ] README is updated with documentation on org / space layer functionality with recommendations for how to leverage the functionality / supported versions
- [ ] Issue created in [docs repo](https://github.com/cyberark/docs-cyberark-conjur-service-broker)  to update tile docs to describe new policy structure and bind behavior

## Task Breakdown
- [x] Ensure existence of organization and space policy / layers
- [x] Generate policy for app membership to space layer
- [x] Update tests for recent PCF and Conjur V5
- [x] Update tests for backward compatible PCF context and Conjur V5
- [x] Verify tests are correct for maintaining Conjur V4 compatibility
- [x] Update README
- [x] Create issues for doc updates
- [ ] Prepare demo

**Comment by jvanderhoof** [comment]
@izgeri, what would the whole bit look like?  For example, if I had a policy w/ database credentials:
```yml
# staging/databases/app-foo/postgres
- !policy
  id: postgres
  body:
    - &variables
      - !variable
        id: username
        annotations:
          description: Database username
      - !variable
        id: password
        annotations:
          description: Database password
      - !variable
        id: url
        annotations:
          description: Database URL
      - !variable
        id: port
        annotations:
          description: Database port

    - !group secrets-users
    - !group secrets-managers

    # secrets-users can read and execute
    - !permit
      resource: *variables
      privileges: [ read, execute ]
      role: !group secrets-users

    # secrets-managers can update (and read and execute, via role grant)
    - !permit
      resource: *variables
      privileges: [ update ]
      role: !group secrets-managers

    # secrets-managers has role secrets-users
    - !grant
      member: !group secrets-managers
      role: !group secrets-users
```

and I setup PCF with the following:

```
org: staging
  space: app-foo
  space: app-bar
```

Next I'd load the CF policy into the `root` policy:
```yml
- !policy
  id: cf
  owner: !group cf-admin-group
  body:
   - !layer cf-apps

   - !host-factory
     id: cf-apps
     layers: [ !layer cf-apps ]

  - !policy
    id: orgs
```

And create org and space layers:
```
- !policy
  id: STAGING_ORG_GUID
  body:
  - !layer

  - !policy
    id: APP-FOO_SPACE_GUID
    body:
    - !layer
    
  - !policy
    id: APP-BAR_SPACE_GUID
    body:
    - !layer
```
Loading the above with: `$ conjur policy load root/cf/orgs ...`

Next, create the permissions to give `app-foo` read/execute permission on the original database credentials:
```
- !grant
  member: !layer /root/cf/orgs/<STAGING_ORG_GUID>/<APP-FOO_SPACE_GUID>
  role: !group /staging/databases/app-foo/postgres/secrets-users
```

Is this what what we're after?
